### ISSUE TITLE
How do I generate external files? Note: cannot resolve the external symbol _main, already star

### ISSUE THREAD

**Issue by 7547** [Lak3/CSGO-InternalExternal#1]
How do I generate external files? Note: cannot resolve the external symbol _main, already star

**Comment by Lak3** [comment]
Sounds like a compiler issue, check your settings and be sure configuration type is dynamic library (.dll). And that the target extension is set to .dll too. If you still get problems with main not being defined you can manually define it in Linker -> Advanced. Also be sure that the platform is set to x86 (32bit).
